### config.py stores paths and textual information separate from the seals_initialize_project.py file, which may draw from this.

import os


# TODOO Make these be autogenerated from a csv. Also make clear what to do with non-mapped classes like water and barren.
btc12_to_seals7_correspondence_data = {}
btc12_to_seals7_correspondence_data[1] = [2, 'cropland_other', 'cropland']
btc12_to_seals7_correspondence_data[2] = [2, 'cropland_2Gbioen', 'cropland']
btc12_to_seals7_correspondence_data[3] = [3, 'grassland', 'grassland']
btc12_to_seals7_correspondence_data[4] = [4, 'forest_unmanaged', 'forest']
btc12_to_seals7_correspondence_data[5] = [4, 'forest_managed', 'forest']
btc12_to_seals7_correspondence_data[6] = [4, 'restored', 'forest']
btc12_to_seals7_correspondence_data[7] = [5, 'other', 'othernat']
btc12_to_seals7_correspondence_data[8] = [1, 'built_up_areas', 'urban']
btc12_to_seals7_correspondence_data[9] = [2, 'abn_cropland_other', 'cropland']
btc12_to_seals7_correspondence_data[10] = [2, 'abn_cropland_2Gbioen', 'cropland']
btc12_to_seals7_correspondence_data[11] = [3, 'abn_grassland', 'grassland']
btc12_to_seals7_correspondence_data[12] = [4, 'abn_forest_managed', 'forest']

btc12_to_seals7_ids_correspondence = {}
btc12_to_seals7_ids_correspondence[1] = [2]
btc12_to_seals7_ids_correspondence[2] = [2]
btc12_to_seals7_ids_correspondence[3] = [3]
btc12_to_seals7_ids_correspondence[4] = [4]
btc12_to_seals7_ids_correspondence[5] = [4]
btc12_to_seals7_ids_correspondence[6] = [4]
btc12_to_seals7_ids_correspondence[7] = [5]
btc12_to_seals7_ids_correspondence[8] = [1]
btc12_to_seals7_ids_correspondence[9] = [2]
btc12_to_seals7_ids_correspondence[10] = [2]
btc12_to_seals7_ids_correspondence[11] = [3]
btc12_to_seals7_ids_correspondence[12] = [4]

btc12_to_seals7_labels_corrspondence = {}
btc12_to_seals7_labels_corrspondence['cropland_other'] =  ['cropland']
btc12_to_seals7_labels_corrspondence['cropland_2Gbioen'] =  ['cropland']
btc12_to_seals7_labels_corrspondence['grassland'] =  ['grassland']
btc12_to_seals7_labels_corrspondence['forest_unmanaged'] =  ['forest']
btc12_to_seals7_labels_corrspondence['forest_managed'] =  ['forest']
btc12_to_seals7_labels_corrspondence['restored'] =  ['forest']
btc12_to_seals7_labels_corrspondence['other'] =  ['othernat']
btc12_to_seals7_labels_corrspondence['built_up_areas'] =  ['urban']
btc12_to_seals7_labels_corrspondence['abn_cropland_other'] =  ['cropland']
btc12_to_seals7_labels_corrspondence['abn_cropland_2Gbioen'] =  ['cropland']
btc12_to_seals7_labels_corrspondence['abn_grassland'] =  ['grassland']
btc12_to_seals7_labels_corrspondence['abn_forest_managed'] =  ['forest']

seals7_to_btc12_ids_correspondence = {}
seals7_to_btc12_ids_correspondence[1] = [8]
seals7_to_btc12_ids_correspondence[2] = [1, 2, 9, 10]
seals7_to_btc12_ids_correspondence[3] = [3, 11]
seals7_to_btc12_ids_correspondence[4] = [4, 5, 6, 12]
seals7_to_btc12_ids_correspondence[5] = [7]
seals7_to_btc12_ids_correspondence[6] = []
seals7_to_btc12_ids_correspondence[7] = []

seals7_to_btc12_labels_correspondence = {}
seals7_to_btc12_labels_correspondence['urban'] = ['built_up_areas']
seals7_to_btc12_labels_correspondence['cropland'] = ['cropland_other', 'cropland_2Gbioen', 'abn_cropland_2Gbioen', 'abn_cropland_other']
seals7_to_btc12_labels_correspondence['grassland'] = ['grassland', 'abn_grassland']
seals7_to_btc12_labels_correspondence['forest'] = ['forest_unmanaged', 'forest_managed', 'restored', 'abn_forest_managed']
seals7_to_btc12_labels_correspondence['othernat'] = ['other']
seals7_to_btc12_labels_correspondence['water'] = []
seals7_to_btc12_labels_correspondence['barren'] = []

# TODOO!! Define corrspondence (1-1) vs reclass 1-many


seals7_ids_to_labels_correspondence = {}
seals7_ids_to_labels_correspondence[1] = 'urban'
seals7_ids_to_labels_correspondence[2] = 'cropland'
seals7_ids_to_labels_correspondence[3] = 'grassland'
seals7_ids_to_labels_correspondence[4] = 'forest'
seals7_ids_to_labels_correspondence[5] = 'othernat'
seals7_ids_to_labels_correspondence[6] = 'water'
seals7_ids_to_labels_correspondence[7] = 'barren'

seals7_labels_to_ids_correspondence = {}
seals7_labels_to_ids_correspondence['urban'] = 1
seals7_labels_to_ids_correspondence['cropland'] = 2
seals7_labels_to_ids_correspondence['grassland'] = 3
seals7_labels_to_ids_correspondence['forest'] = 4
seals7_labels_to_ids_correspondence['othernat'] = 5
seals7_labels_to_ids_correspondence['water'] = 6
seals7_labels_to_ids_correspondence['barren'] = 7



esa_to_seals7_correspondence = {}
esa_to_seals7_correspondence[0] = [0, 'ndv', 'ndv']
esa_to_seals7_correspondence[10] = [2, 'crop_rainfed', 'crop']
esa_to_seals7_correspondence[11] = [2, 'crop_rainfed_herb', 'crop']
esa_to_seals7_correspondence[12] = [2, 'crop_rainfed_tree', 'crop']
esa_to_seals7_correspondence[20] = [2, 'crop_irrigated', 'crop']
esa_to_seals7_correspondence[30] = [2, 'crop_natural_mosaic', 'crop']
esa_to_seals7_correspondence[40] = [2, 'natural_crop_mosaic', 'crop']
esa_to_seals7_correspondence[50] = [4, 'tree_broadleaved_evergreen', 'forest']
esa_to_seals7_correspondence[60] = [4, 'tree_broadleaved_deciduous_closed_to_open_15', 'forest']
esa_to_seals7_correspondence[61] = [4, 'tree_broadleaved_deciduous_closed_40', 'forest']
esa_to_seals7_correspondence[62] = [4, 'tree_broadleaved_deciduous_open_15_40', 'forest']
esa_to_seals7_correspondence[70] = [4, 'tree_needleleaved_deciduous_closed_to_open_15', 'forest']
esa_to_seals7_correspondence[71] = [4, 'tree_needleleaved_evergreen_closed_to_open_15_extended', 'forest']
esa_to_seals7_correspondence[72] = [4, 'tree_needleleaved_evergreen_open_15_40', 'forest']
esa_to_seals7_correspondence[80] = [4, 'tree_needleleaved_deciduous_closed_to_open_15', 'forest']
esa_to_seals7_correspondence[81] = [4, 'tree_needleleaved_deciduous_closed_40', 'forest']
esa_to_seals7_correspondence[82] = [4, 'tree_needleleaved_deciduous_open_15_40', 'forest']
esa_to_seals7_correspondence[90] = [4, 'tree_mixed_type', 'forest']
esa_to_seals7_correspondence[100] = [4, 'mosaic_tree_and_shrub_50_herbaceous_cover_50', 'forest']
esa_to_seals7_correspondence[110] = [5, 'mosaic_herbaceous_cover_50_tree_and_shrub_50', 'shrubland']
esa_to_seals7_correspondence[120] = [5, 'shrubland', 'shrubland']
esa_to_seals7_correspondence[121] = [5, 'evergreen_shrubland', 'shrubland']
esa_to_seals7_correspondence[122] = [5, 'deciduous_shrubland', 'shrubland']
esa_to_seals7_correspondence[130] = [3, 'grassland', 'grassland']
esa_to_seals7_correspondence[140] = [5, 'lichens_and_mosses', 'shrubland']
esa_to_seals7_correspondence[150] = [5, 'sparse_vegetation_tree_shrub_herbaceous_cover_15', 'shrubland']
esa_to_seals7_correspondence[151] = [4, 'sparse_tree_15', 'forest']
esa_to_seals7_correspondence[152] = [5, 'sparse_shrub_15', 'shrubland']
esa_to_seals7_correspondence[153] = [5, 'sparse_herbaceous_cover_15', 'shrubland']
esa_to_seals7_correspondence[160] = [4, 'tree_cover_flooded_fresh_or_brakish_water', 'forest']
esa_to_seals7_correspondence[170] = [4, 'tree_cover_flooded_saline_water', 'forest']
esa_to_seals7_correspondence[180] = [5, 'shrub_or_herbaceous_cover_flooded_fresh_saline_brakish_water', 'shrubland']
esa_to_seals7_correspondence[190] = [1, 'urban_areas', 'urban']
esa_to_seals7_correspondence[200] = [7, 'bare_areas', 'other']
esa_to_seals7_correspondence[201] = [7, 'consolidated_bare_areas', 'other']
esa_to_seals7_correspondence[202] = [7, 'unconsolidated_bare_areas', 'other']
esa_to_seals7_correspondence[210] = [6, 'water_bodies', 'water']
esa_to_seals7_correspondence[220] = [7, 'permanent_snow_and_ice', 'other']

esa_to_seals7_mosaic_is_natural_correspondence = {}
esa_to_seals7_mosaic_is_natural_correspondence[0] = [0, 'ndv', 'ndv']
esa_to_seals7_mosaic_is_natural_correspondence[10] = [2, 'crop_rainfed', 'crop']
esa_to_seals7_mosaic_is_natural_correspondence[11] = [2, 'crop_rainfed_herb', 'crop']
esa_to_seals7_mosaic_is_natural_correspondence[12] = [2, 'crop_rainfed_tree', 'crop']
esa_to_seals7_mosaic_is_natural_correspondence[20] = [2, 'crop_irrigated', 'crop']
esa_to_seals7_mosaic_is_natural_correspondence[30] = [5, 'crop_natural_mosaic', 'shrubland'] # DIFF IS HERE
esa_to_seals7_mosaic_is_natural_correspondence[40] = [4, 'natural_crop_mosaic', 'forest'] # DIFF IS HERE
esa_to_seals7_mosaic_is_natural_correspondence[50] = [4, 'tree_broadleaved_evergreen', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[60] = [4, 'tree_broadleaved_deciduous_closed_to_open_15', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[61] = [4, 'tree_broadleaved_deciduous_closed_40', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[62] = [4, 'tree_broadleaved_deciduous_open_15_40', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[70] = [4, 'tree_needleleaved_deciduous_closed_to_open_15', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[71] = [4, 'tree_needleleaved_evergreen_closed_to_open_15_extended', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[72] = [4, 'tree_needleleaved_evergreen_open_15_40', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[80] = [4, 'tree_needleleaved_deciduous_closed_to_open_15', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[81] = [4, 'tree_needleleaved_deciduous_closed_40', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[82] = [4, 'tree_needleleaved_deciduous_open_15_40', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[90] = [4, 'tree_mixed_type', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[100] = [4, 'mosaic_tree_and_shrub_50_herbaceous_cover_50', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[110] = [5, 'mosaic_herbaceous_cover_50_tree_and_shrub_50', 'shrubland']
esa_to_seals7_mosaic_is_natural_correspondence[120] = [5, 'shrubland', 'shrubland']
esa_to_seals7_mosaic_is_natural_correspondence[121] = [5, 'evergreen_shrubland', 'shrubland']
esa_to_seals7_mosaic_is_natural_correspondence[122] = [5, 'deciduous_shrubland', 'shrubland']
esa_to_seals7_mosaic_is_natural_correspondence[130] = [3, 'grassland', 'grassland']
esa_to_seals7_mosaic_is_natural_correspondence[140] = [5, 'lichens_and_mosses', 'shrubland']
esa_to_seals7_mosaic_is_natural_correspondence[150] = [5, 'sparse_vegetation_tree_shrub_herbaceous_cover_15', 'shrubland']
esa_to_seals7_mosaic_is_natural_correspondence[151] = [4, 'sparse_tree_15', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[152] = [5, 'sparse_shrub_15', 'shrubland']
esa_to_seals7_mosaic_is_natural_correspondence[153] = [5, 'sparse_herbaceous_cover_15', 'shrubland']
esa_to_seals7_mosaic_is_natural_correspondence[160] = [4, 'tree_cover_flooded_fresh_or_brakish_water', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[170] = [4, 'tree_cover_flooded_saline_water', 'forest']
esa_to_seals7_mosaic_is_natural_correspondence[180] = [5, 'shrub_or_herbaceous_cover_flooded_fresh_saline_brakish_water', 'shrubland']
esa_to_seals7_mosaic_is_natural_correspondence[190] = [1, 'urban_areas', 'urban']
esa_to_seals7_mosaic_is_natural_correspondence[200] = [7, 'bare_areas', 'other']
esa_to_seals7_mosaic_is_natural_correspondence[201] = [7, 'consolidated_bare_areas', 'other']
esa_to_seals7_mosaic_is_natural_correspondence[202] = [7, 'unconsolidated_bare_areas', 'other']
esa_to_seals7_mosaic_is_natural_correspondence[210] = [6, 'water_bodies', 'water']
esa_to_seals7_mosaic_is_natural_correspondence[220] = [7, 'permanent_snow_and_ice', 'other']

#ESRI Sentinel
sentinel_class_labels = {}
sentinel_class_labels[1] = 'water'
sentinel_class_labels[2] = 'trees'
sentinel_class_labels[3] = ''
sentinel_class_labels[4] = 'flooded'
sentinel_class_labels[5] = 'crops'
sentinel_class_labels[6] = ''
sentinel_class_labels[7] = 'built'
sentinel_class_labels[8] = 'bare'
sentinel_class_labels[9] = 'ice'
sentinel_class_labels[10] = 'clouds'
sentinel_class_labels[11] = 'range'
"""
1. Water
Areas where water was predominantly present throughout the year; may not cover areas with sporadic or ephemeral water; contains little to no sparse vegetation, no rock outcrop nor built up features like docks; examples: rivers, ponds, lakes, oceans, flooded salt plains.

2. Trees
Any significant clustering of tall (~15 feet or higher) dense vegetation, typically with a closed or dense canopy; examples: wooded vegetation,  clusters of dense tall vegetation within savannas, plantations, swamp or mangroves (dense/tall vegetation with ephemeral water or canopy too thick to detect water underneath).

4. Flooded vegetation
Areas of any type of vegetation with obvious intermixing of water throughout a majority of the year; seasonally flooded area that is a mix of grass/shrub/trees/bare ground; examples: flooded mangroves, emergent vegetation, rice paddies and other heavily irrigated and inundated agriculture.

5. Crops
Human planted/plotted cereals, grasses, and crops not at tree height; examples: corn, wheat, soy, fallow plots of structured land.

7. Built Area
Human made structures; major road and rail networks; large homogenous impervious surfaces including parking structures, office buildings and residential housing; examples: houses, dense villages / towns / cities, paved roads, asphalt.

8. Bare ground
Areas of rock or soil with very sparse to no vegetation for the entire year; large areas of sand and deserts with no to little vegetation; examples: exposed rock or soil, desert and sand dunes, dry salt flats/pans, dried lake beds, mines.

9. Snow/Ice
Large homogenous areas of permanent snow or ice, typically only in mountain areas or highest latitudes; examples: glaciers, permanent snowpack, snow fields.
 
10. Clouds
No land cover information due to persistent cloud cover.

11. Rangeland
Open areas covered in homogenous grasses with little to no taller vegetation; wild cereals and grasses with no obvious human plotting (i.e., not a plotted field); examples: natural meadows and fields with sparse to no tree cover, open savanna with few to no trees, parks/golf courses/lawns, pastures. Mix of small clusters of plants or single plants dispersed on a landscape that shows exposed soil or rock; scrub-filled clearings within dense forests that are clearly not taller than trees; examples: moderate to sparse cover of bushes, shrubs and tufts of grass, savannas with very sparse grasses, trees or other plants.
"""

# copernicus classes, 100m 2015-2019
"""
Value	Color	Color Code	Label
0		0x282828	No input data available
20		0xffbb22	Shrubs
30		0xffff4c	Herbaceous vegetation
40		0xf096ff	Cultivated and managed vegetation/agriculture (cropland)
50		0xfa0000	Urban / built up
60		0xb4b4b4	Bare / sparse vegetation
70		0xf0f0f0	Snow and Ice
80		0x0032c8	Permanent water bodies
90		0x0096a0	Herbaceous wetland
100		0xfae6a0	Moss and lichen
111		0x58481f	Closed forest, evergreen needle leaf
112		0x009900	Closed forest, evergreen, broad leaf
113		0x70663e	Closed forest, deciduous needle leaf
114		0x00cc00	Closed forest, deciduous broad leaf
115		0x4e751f	Closed forest, mixed
116		0x007800	Closed forest, unknown
121		0x666000	Open forest, evergreen needle leaf
122		0x8db400	Open forest, evergreen broad leaf
123		0x8d7400	Open forest, deciduous needle leaf
124		0xa0dc00	Open forest, deciduous broad leaf
125		0x929900	Open forest, mixed
126		0x648c00	Open forest, unknown
200		0x000080	Open sea
255			No data
"""


# World Cover 2020

seea_land_use_classification = {}

"""
1 Land
1.1 Agriculture
1.2 Forestry
1.3 Land used for aquaculture
1.4 Use of built-up and related areas
1.5 Land used for maintenance and restoration of environmental functions
1.6 Other uses of land n.e.c.
1.7 Land not in use
2 Inland waters
2.1 Inland waters used for aquaculture or holding facilities
2.2 Inland waters used for maintenance and restoration of environmental functions
2.3 Other uses of inland waters n.e.c.
2.4 Inland waters not in use
"""

seea_land_cover_classification = {}

"""
1 Artificial surfaces (including urban and associated areas)
2 Herbaceous crops
3 Woody crops
4 Multiple or layered crops
5 Grassland
6 Tree-covered areas
7 Mangroves
8 Shrub-covered areas
9 Shrubs and/or herbaceous vegetation, aquatic or regularly flooded
10 Sparsely natural vegetated areas
11 Terrestrial barren land
12 Permanent snow and glaciers
13 Inland water bodies
14 Coastal water bodies and intertidal areas
"""

# FAO seea compatible
"""
1 Artificial surfaces (including urban and associated areas)
2 Herbaceous crops
3 Woody crops
4 Multiple or layered crops
Grassland
Tree-covered areas
Mangroves
Shrub-covered areas
Shrubs and/or herbaceous vegetation, aquatic or regularly flooded
Sparsely natural vegetated areas
Terrestrial barren land
Permanent snow and glaciers
Inland water bodies
Coastal water bodies and intertidal areas
"""


"""
seasonal water yield - hydropower too hard, what about irrigation?
nutrient- if exports to streams increases, water quality decreases, thus impacting water treatment cost shock to utilities, also tourism and recreation.
sdr
carbon, damage function.
pollionation?

thinking about:
coastal protection, mangroves

roastman and sartori, parameterized damage functions for coastal protection
"""
























